AWSTemplateFormatVersion: '2010-09-09'
Description: 'Panaptico Mission: KMS Key for EBS Encryption.'

Parameters:
  KeyDeletionWindowInDays:
    Type: Number
    Default: 7
    Description: The waiting period, in days, before deleting the key.

Resources:
  EbsEncryptionKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: 'KMS key for encrypting EBS volumes for migrated EC2 instances'
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: 'Enable IAM User Permissions'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
      EnableKeyRotation: true
      PendingWindowInDays: !Ref KeyDeletionWindowInDays
      Tags:
        - Key: Name
          Value: 'panaptico-ebs-encryption-key'
        - Key: panaptico-mission-id
          Value: 'ec2-migration-0d192e18'

  EbsEncryptionKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: 'alias/panaptico/ebs-encryption'
      TargetKeyId: !Ref EbsEncryptionKey

Outputs:
  KeyId:
    Description: The ID of the KMS Key.
    Value: !Ref EbsEncryptionKey
    Export:
      Name: !Sub '${AWS::StackName}-KeyId'
  KeyArn:
    Description: The ARN of the KMS Key.
    Value: !GetAtt EbsEncryptionKey.Arn
    Export:
      Name: !Sub '${AWS::StackName}-KeyArn'
